
export enum AssetType {
  STOCK = 'Ações',
  FII = 'Fundos Imobiliários',
  ETF = 'ETFs',
  FIXED = 'Renda Fixa',
  CRYPTO = 'Criptomoedas',
  OTHERS = 'Outros'
}

export interface AssetClass {
  id: string;
  name: string;
  targetPercent: number;
}

export interface Asset {
  id: string;
  name: string;
  ticker?: string;
  type: AssetType;
  classId: string;
  notes?: string;
  quantity: number;
  purchaseDate: string; 
  purchasePrice: number;
  currentPrice: number;
  isManualPrice: boolean;
  lastUpdate?: number;
  // targetPercent: Target allocation percentage within its AssetClass
  targetPercent: number;
}

export interface Earning {
  id: string;
  assetTicker: string;
  date: string;
  type: 'Dividendo' | 'JCP' | 'Rendimento' | 'Outro';
  receivedAmount: number;
  reinvestedAmount: number;
  withdrawnAmount: number;
  unitAmount?: number;      
  quantityAtDate?: number; 
  isAutoGenerated?: boolean;
}

export interface Contribution {
  id: string;
  date: string;
  totalAmount: number;
  outOfPocketAmount: number;
  reinvestedAmount: number;
  details: {
    assetId: string;
    ticker: string;
    quantity: number;
    price: number;
  }[];
}

export interface Notification {
  id: string;
  type: 'earning' | 'price_target' | 'allocation';
  title: string;
  message: string;
  timestamp: number;
  isRead: boolean;
  severity: 'low' | 'medium' | 'high';
}

export interface PortfolioSummary {
  totalWealth: number;
  totalInvested: number; 
  totalReinvested: number; 
  realProfitability: number;
  capitalGainPercent: number;
  earningsYieldPercent: number;
  totalEarnings: number;
  reinvestedEarnings: number;
  totalWithdrawn: number;
  notifications: Notification[];
}

export interface BenchmarkPoint {
  label: string;
  carteira: number;
  cdi?: number;
  ipca?: number;
  ibov?: number;
  ifix?: number;
  sp500?: number;
  nasdaq?: number;
  poupanca?: number;
}
